language: node_js
node_js: 10

install:
  - npm ci

script:
  - npx nps build
  - npx nps test.coverage

after_success:
  - npm install codacy-coverage
  - npx codacy-coverage -v < ./coverage/lcov.info

cache:
  directories:
    - node_modules
