name: CI
on: [push]
jobs:
  ci:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci --ignore-scripts
    - name: Build
      run: npx nps build
    - name: Test
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      run: |
        npx nps test.coverage
        npx codacy-coverage -v < ./coverage/lcov.info
